FROM gradle:8.5-jdk11 AS builder

WORKDIR /app
COPY build.gradle settings.gradle ./
COPY src ./src

RUN gradle build --no-daemon -x test

FROM scratch AS export
COPY --from=builder /app/build/libs/*.jar /
