bootstrap.servers= kafka:9092
# consumer.group.id=group  # will use `connect-sink.test1`

key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000

plugin.path=/usr/share/java,/usr/share/confluent-hub-components
