# SINK CONFIG
name=sink.test1

# CONSUMER CONFIG
topics=test1

# PRODUCER CONFIG
connector.class=org.apache.iceberg.connect.IcebergSinkConnector
tasks.max=1
# iceberg.table.name=default_database.test1
iceberg.tables=default_database.test1
# iceberg.tables.dynamic-enabled=true

# iceberg.catalog.type=rest
# iceberg.catalog.rest.uri=http://iceberg:8181
# iceberg.catalog.rest.warehouse=s3://bucket/warehouse/
# iceberg.catalog.credential="<credential>"


# S3 Configuration
iceberg.catalog.s3.endpoint=http://minio:9000
iceberg.catalog.s3.path-style-access=true
iceberg.catalog.s3.access-key-id=minioadmin
iceberg.catalog.s3.secret-access-key=minioadmin
iceberg.catalog.s3.region=us-east-1

# Catalog name
iceberg.catalog.catalog-impl=org.apache.iceberg.rest.RESTCatalog
iceberg.catalog.uri=http://iceberg:8181
iceberg.catalog.warehouse=s3://bucket/warehouse/

iceberg.tables.auto-create-enabled=true
iceberg.tables.evolve-schema-enabled=true
iceberg.control.commit.interval-ms=10000
iceberg.control.commit.timeout-ms=30000
# iceberg.tables.schema-force-optional=true